services:
  - docker

before_install:
  - docker build -t reactdev/latest .
  - docker build -f bld.Dockerfile .

script:
  - timeout 30 docker run reactdev/latest
  - timeout 30 docker run bld.Dickerfile ; exit 0