const CHANGE_FILTER = 'CHANGE_FILTER';
const GET_TODOS_SUCCESS = 'GET_TODOS_SUCCESS';
const GET_TODOS_REQUEST = 'GET_TODOS_REQUEST';
const GET_TODOS_FAILURE = 'GET_TODOS_FAILURE';
const PATCH_TODO_COMPLETED_REQUEST = 'PATCH_TODO_COMPLETED';
const PATCH_TODO_COMPLETED_SUCCESS = 'PATCH_TODO_COMPLETED_SUCCESS';
const PATCH_TODO_COMPLETED_FAILURE = 'PATCH_TODO_COMPLETED_FAILURE';
const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST';
const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
const DELETE_TODO_FAILURE = 'DELETE_TODO_FAILURE';
const POST_TODO_REQUEST = 'POST_TODO_REQUEST';
const POST_TODO_SUCCESS = 'POST_TODO_SUCCESS';
const POST_TODO_FAILURE = 'POST_TODO_FAILURE';
const SHOW_ALL = 'SHOW_ALL';
const SHOW_TODO = 'SHOW_TODO';
const SHOW_DONE = 'SHOW_DONE';


export default {
    CHANGE_FILTER,
    GET_TODOS_SUCCESS,
    GET_TODOS_REQUEST,
    GET_TODOS_FAILURE,
    PATCH_TODO_COMPLETED_REQUEST,
    PATCH_TODO_COMPLETED_SUCCESS,
    PATCH_TODO_COMPLETED_FAILURE,
    DELETE_TODO_REQUEST,
    DELETE_TODO_SUCCESS,
    DELETE_TODO_FAILURE,
    POST_TODO_REQUEST,
    POST_TODO_SUCCESS,
    POST_TODO_FAILURE,
    SHOW_ALL,
    SHOW_TODO,
    SHOW_DONE
};